version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: backend/Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - uploads_data:/usr/src/app/backend/uploads
      - /root/app/Wav2Lip:/wav2lip
    env_file:
      - .env
    restart: unless-stopped

volumes:
  uploads_data:
